<div class="container">
    <div class="table-responsive-sm" style="width: 100%; overflow: auto; max-height: 800px;">
    <table class="table">
        <thead>
            <tr>
                <th style="text-align: center;">Operater</th>
                <th style="text-align: center;">OIB</th>
                <th style="text-align: center;">Email</th>
                <th style="text-align: center;">Uloga</th>
                <?php if ($_SESSION['operater']->uloga == 'superadmin')
                    echo '<th style="text-align: center;">Naziv tvrtke</th>';
                ?>
                <?php if ($_SESSION['operater']->uloga == 'Admin' || $_SESSION['operater']->uloga == 'superadmin')
                    echo '<th style="text-align: center;">Akcija</th>';
                ?>
            </tr>
        </thead>
        <tbody>
        <?php 
            if ($_SESSION['operater']->uloga == 'Admin'){
                foreach($operateri as $red){
                    include 'operateristavke.phtml';
                }
            }
            else if ($_SESSION['operater']->uloga == 'superadmin'){
                foreach($operateri as $red){
                    include 'operateristavke.phtml';
                }
            }
            ?>
        </tbody>
    </table>
    </div>
</div>