<tr>
    <td style="text-align: center;" title="Naziv tvrtke"><?php echo $red->nazivtvrtke?></td>
    <td style="text-align: center;" title="OIB"><?php echo $red->oib?></td>
    <td style="text-align: center;" title="Adresa"><?php echo $red->adresa?></td>
    <td style="text-align: center;" title="Telefon"><?php echo $red->telefon?></td>
    <td style="text-align: center;" title="Email"><?php echo $red->email?></td>
    <td style="text-align: center;" title="Mjesto"><?php echo $red->imemjesta?></td>
    <td style="text-align: center;" title="Poštanski broj"><?php echo $red->postanskibroj?></td>
    <td style="text-align: center;" title="Država"><?php echo $red->imedrzave?></td>
    <td style="text-align: center;">    <a href="/admini/partneripromjena?partner_id=<?php echo $red->partner_id?>"><i title="Promijeni" class="fas fa-edit fa-2x"></i></a> 
            <a onclick="return confirm('Sigurno obrisati <?php echo $red->nazivtvrtke ?>?');" href="/admini/partneriobrisi?partner_id=<?php echo $red->partner_id?>"><i title="Obriši" class="fas fa-trash fa-2x" style="color: red;"></i></a>
    </td>
</tr>

