<form method="POST" action="/admini/partneriedit">
    <div class="form-row justify-content-center">
    <div class="form-group col-md-6">
      <label for="naziv">Naziv</label>
      <input type="text" class="form-control" id="nazivpartnera" name="nazivpartnera" value="<?php echo $partner->nazivtvrtke?>">
    </div>
</div>

<div class="form-row justify-content-center">
    <div class="form-group col-md-6">
      <label for="oib">OIB</label>
      <input type="text" class="form-control" id="oibpartnera" name="oibpartnera" value="<?php echo $partner->oib?>">
    </div>
</div>

<div class="form-row justify-content-center">
    <div class="form-group col-md-6">
      <label for="adresa">Adresa</label>
      <input type="text" class="form-control" id="adresapartnera" name="adresapartnera" value="<?php echo $partner->adresa?>">
    </div>
</div>

<div class="form-row justify-content-center">
    <div class="form-group col-md-6">
      <label for="telefon">Telefon</label>
      <input type="text" class="form-control" id="telefonpartnera" name="telefonpartnera" value="<?php echo $partner->telefon?>">
    </div>
</div>

<div class="form-row justify-content-center">
    <div class="form-group col-md-6">
      <label for="email">Email</label>
      <input type="email" class="form-control" id="emailpartnera" name="emailpartnera" value="<?php echo $partner->email?>">
    </div>
</div>

<div class="form-row justify-content-center">
<div class="form-group col-md-6">
  <select class="form-control" id="mjesto" name="mjesto">
  <option value="0">Odaberite mjesto</option>
    <?php foreach($mjesta as $mjesto): ?>
      <option value="<?php echo $mjesto->mjesto_id ?>">
        <?php echo $mjesto->naziv ?>
      </option>
    <?php endforeach;?>
    </select>
  </div>
  </div>

<div class="text-center">
      <button class="btn btn-primary">Promijeni podatke</button>
</div>
<input type="hidden" name="partner_id" value="<?php echo $partner->partner_id?>">
<input type="hidden" name="tvrtka_id" value="<?php echo $_SESSION['operater']->tvrtka_id?>">
</form>

<?php if(isset($alertPoruka)): ?>
    <script>
        	alert("<?php echo $alertPoruka ?>");
    </script>
<?php endif;?>
