<tr>
    <td style="text-align: center;" title="Poštanski broj"><?php echo $mjesto->postanskibroj?></td>
    <td style="text-align: center;" title="Naziv mjesta"><?php echo $mjesto->naziv?></td>
    <td style="text-align: center;" title="Naziv države"><?php echo $mjesto->nazivdrzave?></td>
    <td style="text-align: center;">    <a href="/sifarnik/mjestopromjena?mjesto_id=<?php echo $mjesto->mjesto_id?>"><i title="Promijeni" class="fas fa-edit fa-2x"></i></a> 
            <a onclick="return confirm('Sigurno obrisati <?php echo $mjesto->naziv?>?');" href="/sifarnik/mjestoobrisi?mjesto_id=<?php echo $mjesto->mjesto_id?>"><i title="Obriši" class="fas fa-trash fa-2x" style="color: red;"></i></a>
    </td>
</tr>

