<div class="jumbotron">
  <h1 class="display-4"><?php echo isset($_SESSION['operater']) ? 'Dobrodošli nazad ' . $_SESSION['operater']->ime . ' ' . $_SESSION['operater']->prezime . '!': 'Niste prijavljeni'?></h1>
  <p class="lead">Ovo je web-aplikacija izrađena za završni rad na PHP programiranju</p>
  <hr class="my-4">
  <p>Polaznik sam grupe PP20</p>
  <a class="btn btn-primary btn-lg" href="https://www.edunova.hr/" role="button">Više...</a>
</div>