<div class="jumbotron">
  <h1 class="display-4"><?php echo isset($_SESSION['operater']) ? $poruka : 'Niste prijavljeni'?></h1>
  <p class="lead">Ovo je završni rad za PHP programiranje</p>
  <hr class="my-4">
  <p>Polaznik sam grupe PP20</p>
  <a class="btn btn-primary btn-lg" href="http://www.edunova.hr" role="button">Više...</a>
</div>

<?php if(isset($alertPoruka)): ?>
    <script>
        	alert("<?php echo $alertPoruka ?>");
    </script>
<?php endif;?>

