<!doctype html>
<html class="no-js" lang="en" dir="ltr">
  <head>
    <?php include_once 'predlozak/head.phtml'; ?>
  </head>
  <body>
  <?php require_once 'predlozak/izbornik.phtml' ?>
     <!-- Početak tijela -->
     <div class="container">
      <?php 
        echo $sadrzaj; 
      ?>
    </div>
      <!-- Kraj tijela -->
      </body>
      <?php require_once 'predlozak/podnozje.phtml' ?> 
    <?php require_once 'predlozak/skripte.phtml' ?>
</html>
