<form method="POST" action="/operater/dodajnovi">
  <div class="form-row">
    <div class="form-group col-md-6">
      <label for="email">Email</label>
      <input type="email" class="form-control" id="email">
    </div>
    <div class="form-group col-md-6">
      <label for="username">Korisničko ime</label>
      <input type="text" class="form-control" id="username">
    </div>
  </div>
    <div class="form-row">
      <div class="form-group col-md-6">
        <label for="pass">Lozinka</label>
        <input type="password" class="form-control" id="pass">
      </div>
      <div class="form-group col-md-6">
        <label for="lozinkaponovo">Potvrdite lozinku</label>
        <input type="password" class="form-control" id="lozinkaponovo">
      </div>
  </div>
  <button type="submit" class="btn btn-primary">Registriraj se</button>
</form>