<form action="/index/autorizacija">
  <div class="form-row">
    <div class="form-group col-md-6">
      <label for="inputEmail4">Email</label>
      <input type="email" class="form-control" id="inputEmail4">
    </div>
    <div class="form-group col-md-6">
      <label for="inputPassword4">Lozinka</label>
      <input type="password" class="form-control" id="inputPassword4">
    </div>
  </div>
  <div class="form-group">
    <label for="inputAddress">Adresa</label>
    <input type="text" class="form-control" id="inputAddress">
  </div>
  <div class="form-row">
    <div class="form-group col-md-6">
      <label for="inputCity">Mjesto</label>
      <input type="text" class="form-control" id="inputCity">
    </div>
    <div class="form-group col-md-4">
      <label for="inputState">Država</label>
      <select id="inputState" class="form-control">
        <option selected>Odaberi...</option>
        <option></option>
      </select>
    </div>
    <div class="form-group col-md-2">
      <label for="inputZip">Poštanski broj</label>
      <input type="text" class="form-control" id="inputZip">
    </div>
  </div>
  <button type="submit" class="btn btn-primary">Registriraj se</button>
</form>