<form method="POST" action="/index/zavrsiregistraciju">
    <div class="form-row justify-content-center">
    <div class="form-group col-md-6">
      <label for="email">Email</label>
      <input type="email" class="form-control" id="email" name="email">
    </div>
</div>

<div class="form-row justify-content-center">
    <div class="form-group col-md-6">
      <label for="lozinka">Lozinka</label>
      <input type="password" class="form-control" id="lozinka" name="lozinka">
    </div>
    </div>

    <div class="form-row justify-content-center">
    <div class="form-group col-md-6">
      <label for="lozinka">Lozinka ponovo</label>
      <input type="password" class="form-control" id="lozinkaponovo" name="lozinkaponovo">
    </div>
    </div>

<div class="text-center">
      <button class="btn btn-primary">Započnite registraciju</button>
</div>
</form>

<?php if(isset($alertPoruka)): ?>
    <script>
        	alert("<?php echo $alertPoruka ?>");
    </script>
<?php endif;?>


