<nav class="navbar navbar-expand-lg sticky-top navbar-light bg-light">
  <a class="navbar-brand" href="/index"><?php echo APP::config('nazivAPP');?></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="/index">Početna</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/index/onama">O nama</a>
      </li>
      <?php if(isset($_SESSION['operater'])): ?>
        <?php if ($_SESSION['operater']->uloga == 'oper') : ?>
          <li class="nav-item">
          <a class="nav-link" href="/index">Kontakti</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/index">Početna</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/index">Početna</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/index">Početna</a>
        </li>
        <?php endif; ?>
        <?php if ($_SESSION['operater']->uloga == 'admin') : ?>
          <li class="nav-item">
            <a class="nav-link" href="/index">Kontakti</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/index">Korisnici</a>
          </li>
        <?php endif; ?>
    </ul>
    <?php endif; ?>
    <?php if (!isset($_SESSION['operater'])) :?>
    <form class="form-inline my-2 my-lg-0" method="POST" action="/index/autorizacija">
  <label class="sr-only" for="email">Korisničko ime</label>
  <div class="input-group mb-2 mr-sm-2">
    <input type="text" class="form-control" id="email" name="email" placeholder="Korisničko ime">
  </div>

  <label class="sr-only" for="lozinka">Lozinka</label>
  <div class="input-group mb-2 mr-sm-2">
    <input type="password" class="form-control" id="lozinka" name="lozinka" placeholder="Lozinka">
  </div>

  <div class="form-group form-check">
    <input type="checkbox" class="form-check-input" id="exampleCheck1">
    <label class="form-check-label" for="exampleCheck1">Zapamti me</label>
  </div>

  <button type="submit" class="btn btn-primary mb-2">Prijava</button>
  <?php endif; ?>
</form>
  <?php 
       if (isset($_SESSION['operater'])) :
    ?>
    <a href="/index/odjava">Odjava</a>
    <?php endif; ?>
    </div>
</nav>