<nav class="navbar navbar-expand-lg sticky-top navbar-light bg-light">
  <a class="navbar-brand" href="/index"><?php echo APP::config('nazivAPP');?></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="/index">Početna</a>
      </li>
      <?php if (isset($_SESSION['operater'])) :?>
      <li class="nav-item">
        <a class="nav-link" href="/index/profil">Profil</a>
      </li>
      <?php endif; ?>

    </ul>

      <ul class="navbar-nav ml-auto">
      <li>
      <?php if (!isset($_SESSION['operater'])) :?>
    <form class="form-inline my-2 my-lg-0" method="POST" action="/index/?>">
  <label class="sr-only" for="username">Korisničko ime</label>
  <div class="input-group mb-2 mr-sm-2">
    <input type="text" class="form-control" id="username" name="username" placeholder="Korisničko ime">
  </div>

  <label class="sr-only" for="lozinka">Lozinka</label>
  <div class="input-group mb-2 mr-sm-2">
    <input type="password" class="form-control" id="lozinka" name="lozinka" placeholder="Lozinka">
  </div>
  
  <button type="submit" class="btn btn-primary mb-2 mx-2" name="btnPrijava" formaction="/index/autorizacija">Prijava</button>
  <button type="submit" class="btn btn-primary mb-2 mx-2" name="btnRegistracija" formaction="/index/zapocniregistraciju">Registracija</button>
  <?php endif; ?>
</form>

</li>
</ul>
  <?php 
       if (isset($_SESSION['operater'])) :
    ?>
    <a href="/index/odjava">Odjava</a>
    <?php endif; ?>
    </div>
</nav>
