<form method="POST" action="/promjena">

<div class="form-row justify-content-center">
    <div class="form-group col-md-6">
      <label for="prezime">Prezime</label>
      <input type="text" class="form-control" id="prezime" name="prezime" value="<?php echo $_SESSION['operater']->prezime?>">
    </div>
</div>

<div class="form-row justify-content-center">
    <div class="form-group col-md-6">
      <label for="ime">Ime</label>
      <input type="text" class="form-control" id="ime" name="ime" value="<?php echo $_SESSION['operater']->ime?>">
    </div>
</div>

<div class="text-center">
      <button class="btn btn-primary">Spremite promjene</button>
</div>

</form>

<?php if(isset($alertPoruka)): ?>
    <script>
        	alert("<?php echo $alertPoruka ?>");
    </script>
<?php endif;?>
