<form method="POST" action="/napomena/dodaj">
<div class="form-row justify-content-center">
<div class="form-group col-md-6">
  <select class="form-control" id="partner" name="partner">
  <option value="0">Odaberite partnera</option>
    <?php foreach($partneri as $partner): ?>
      <option value="<?php echo $partner->partner_id ?>">
        <?php echo $partner->nazivtvrtke ?>
      </option>
    <?php endforeach;?>
    </select>
  </div>
  </div>

<div class="form-row justify-content-center">
<div class="form-group col-md-6">
<label for="datepicker">Kada kontaktirati:</label> 
<input type="text" id="datepicker"></p>
</div>
</div>
<div class="form-row justify-content-center">
<div class="form-group col-md-6">
<label for="napomena">Napomena:</label>
<textarea id="napomena" class="form-control rounded-0" rows="15"></textarea>
</div>
</div>

<div class="text-center">
      <button class="btn btn-primary">Dodaj napomenu</button>
</div>
</form>

<?php if(isset($alertPoruka)): ?>
    <script>
        alert("<?php echo $alertPoruka ?>");
    </script>
<?php endif;?>
