<form method="POST" action="/napomena/edit">
<div class="form-row justify-content-center">
<div class="form-group col-md-6">
  <select class="form-control" id="partner" name="partner">
  <option value="0">Odaberite partnera</option>
    <?php foreach($partneri as $partner): ?>
      <option value="<?php echo $partner->partner_id ?>">
        <?php echo $partner->nazivtvrtke ?>
      </option>
    <?php endforeach;?>
    </select>
  </div>
  </div>

<div class="form-row justify-content-center">
<div class="form-group col-md-6">
<label for="datepicker">Kada kontaktirati:</label> 
<div class="input-group">
            <input type="text" class="form-control docs-date" name="date" placeholder="Odaberite datum" autocomplete="off">
            <div class="input-group-append">
              <button type="button" class="btn btn-outline-secondary docs-datepicker-trigger" disabled="">
                <i class="fa fa-calendar" aria-hidden="true"></i>
              </button>
            </div>
          </div>
</div>
</div>
<div class="form-row justify-content-center">
<div class="form-group col-md-6">
<label for="napomena">Napomena:</label>
<textarea name="napomena"id="napomena" class="form-control rounded-0" rows="15"><?php echo html_entity_decode($napomena->poruka)?></textarea>
</div>
</div>

<div class="text-center">
      <button class="btn btn-primary">Promijeni napomenu</button>
</div>
<input type="hidden" name="napomena_id" value="<?php echo $napomena->napomena_id?>">
</form>

<?php if(isset($alertPoruka)): ?>
    <script>
        alert("<?php echo $alertPoruka ?>");
    </script>
<?php endif;?>
